apiVersion: batch/v1
kind: Job
metadata:
  generateName: notify-slack-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: slack-notifier
        image: curlimages/curl:8.6.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"âœ… ArgoCD Sync completed successfully!"}' \
          https://hooks.slack.com/services/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
      restartPolicy: Never
  backoffLimit: 1
